name: Synthetic Data Generator
description: |
  Generate privacy-safe synthetic data from CDP Iceberg datasets.
  Preserves statistical properties for ML training while ensuring data privacy.

author: Data Team
specification_version: 1.0

runtimes:
  - editor: Workbench
    kernel: Python 3.10
    edition: Standard
    version: 2024.02
    addons:
      - spark320-cdh3171

environment_variables:
  PYTHONPATH: /home/cdsw

tasks:
  - type: run_application
    name: Launch Synthetic Data Generator
    entity_label: synthetic_data_generator
    script: launch_app.py
    short_summary: Web UI for synthetic data generation
    long_summary: |
      Interactive UI for generating synthetic data from CDP Iceberg tables.
      Supports automatic data profiling, multiple generation methods, and quality reports.
    cpu: 2
    memory: 8
    environment:
      TASK_TYPE: APPLICATION
